app:
  name: 'go-clean-template'
  version: '1.7.1 from Mar 08, 2025'

http:
  port: '8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-clean-template'

postgres:
  pool_max: 2
  pg_url: 'postgresql://user:myAwEsOm3pa55@w0rd@localhost:5432/db'

rabbitmq:
  rpc_server_exchange: 'rpc_server'
  rpc_client_exchange: 'rpc_client'
  pmq_url: 'amqp://guest:guest@localhost:5672/'